config/routes.rb
class MainSite
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Saas::Application.routes.draw do

  devise_for :saas_admins
  mount RailsAdmin::Engine => '/saas_admin', :as => 'rails_admin'

  constraints MainSite do
    get '/' => "content#index"

    %w(about privacy).each do |page|
      get page => "content##{page}"
    end

    get '/signup' => 'accounts#plans', :as => 'plans'
    get '/signup/d/:discount' => 'accounts#plans'
    get '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    post '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    get '/signup/:plan/:discount' => 'accounts#new'
    get '/signup/:plan' => 'accounts#new', :as => 'new_account'

  end

  root :to => "accounts#dashboard"

  devise_for :users

  resources :users
  resource :account do
    member do
      get :dashboard, :thanks, :plans, :canceled
      match 'billing' => "accounts#billing", via: [ :get, :post ]
      match 'plan' => "accounts#plan", via: [ :get, :post ]
      match 'cancel' => "accounts#cancel", via: [ :get, :post ]
    end
  end

end

app/controllers/content_controller.rb
# This controller is used to serve (mostly) static pages that are
# the front-end of your site.  For example, the index action is your landing
# page.
class ContentController < ApplicationController
  skip_before_filter :authenticate_user!
  skip_before_filter :collect_billing_info
end

app/views/content/about.html.erb
<h1>About Us</h1>

<p>
  Put some fantastic copy here.
</p>

app/views/content/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Hello, world!</h1>
    <p>This would be your public landing page. Find it in app/views/content/index.html.erb.</p>
    <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
  </div>
</div>

<!-- Example row of columns -->
<div class="row">
  <div class="col-md-6">
    <h2>Powerful headline here</h2>
    <p>You could explain why your app is so awesome.</p>
    <p><%= link_to('Sign up for a new account', plans_path, class: "btn btn-default") %></p>
  </div>
  <div class="col-md-6">
    <h2>Admin access</h2>
    <% if admin = SaasAdmin.first %>
      <p>You can check out the admin area with the login <strong><%= admin.email %></strong> and the password provided by <code>rake saas:bootstrap</code></p>
      <p><%= link_to('Sign in', '/saas_admin', class: "btn btn-default") %></p>
    <% else %>
      <p>You should run <code>rake saas:bootstrap</code> (as mentioned in the README) to generate an admin login</p>
    <% end %>
  </div>
</div>

app/views/content/privacy.html.erb
<h1>Privacy Policy</h1>

<p>
  We value your privacy, and we sell it accordingly. :)
</p>