config/routes.rb
class MainSite
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Saas::Application.routes.draw do

  devise_for :saas_admins
  mount RailsAdmin::Engine => '/saas_admin', :as => 'rails_admin'

  constraints MainSite do
    get '/' => "content#index"

    %w(about privacy).each do |page|
      get page => "content##{page}"
    end

    get '/signup' => 'accounts#plans', :as => 'plans'
    get '/signup/d/:discount' => 'accounts#plans'
    get '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    post '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    get '/signup/:plan/:discount' => 'accounts#new'
    get '/signup/:plan' => 'accounts#new', :as => 'new_account'

  end

  root :to => "accounts#dashboard"

  devise_for :users

  resources :users
  resource :account do
    member do
      get :dashboard, :thanks, :plans, :canceled
      match 'billing' => "accounts#billing", via: [ :get, :post ]
      match 'plan' => "accounts#plan", via: [ :get, :post ]
      match 'cancel' => "accounts#cancel", via: [ :get, :post ]
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base

  has_many :users, :dependent => :destroy, :inverse_of => :account
  has_one :admin, -> { where(admin: true) }, :class_name => "User"
  accepts_nested_attributes_for :admin

  #
  # Set up the account to own subscriptions. An alternative would be to
  # call 'has_subscription' on the user model, if you only want one user per
  # subscription.
  #
  # The limits hash is used to add some methods to the class that you can
  # use to check whether the subscriber has the rights to do something.
  # The hash keys match the *_limit fields in the subscriptions and
  # subscription_plan tables, and the values are the methods that will be
  # called to see if that limit has been reached.  For example,
  #
  # { 'user_limit' => Proc.new {|a| a.users.count } }
  #
  # defines a single limit based on the user_limit attribute that would
  # call users.account on the instance of the model that is invoking this
  # method.  In other words, if you have this:
  #
  # class Account < ActiveRecord::Base
  #   has_subscription({ 'user_limit' => Proc.new {|a| a.users.count } })
  # end
  #
  # then you could call @account.reached_user_limit? to know whether to allow
  # the account to create another user (a.users.count < subscription.user_limit).
  #
  # To add additional limits, add a field named *_limit (like project_limit)
  # to the subscriptions and subscription_plans table in a migration, and
  # add it to the hash here.  The value of the field in the subscription_plans table
  # will be the default for the account's subscription when the subscription
  # is created, so you define your tiers by the different values
  # of the *_limit plans in the subscription_plans table.
  has_subscription :user_limit => Proc.new {|a| a.users.count }

  #
  # The model with "has_subscription" needs to provide an email attribute.
  # But ours is stored in the user model, so we delegate
  #
  def email
    admin.try(:email)
  end

  validates_presence_of :admin, :message => "information is missing"
  validates_associated :admin
  validates_format_of :domain, :with => /\A[a-zA-Z][a-zA-Z0-9]*\Z/
  validates_exclusion_of :domain, :in => %W( support blog www billing help api ), :message => "The domain <strong>{{value}}</strong> is not available."
  validate :valid_domain?

  def domain
    @domain ||= self.full_domain.blank? ? '' : self.full_domain.split('.').first
  end

  def domain=(domain)
    @domain = domain
    self.full_domain = "#{domain}.#{Saas::Config.base_domain}"
  end

  def to_s
    name.blank? ? full_domain : "#{name} (#{full_domain})"
  end

  protected

    def valid_domain?
      conditions = new_record? ? ['full_domain = ?', self.full_domain] : ['full_domain = ? and id <> ?', self.full_domain, self.id]
      self.errors.add(:domain, 'is not available') if self.full_domain.blank? || self.class.where(conditions).count > 0
    end

  rails_admin do
    object_label_method :full_domain
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  inherit_resources

  before_filter :authenticate_user!, :except => [ :new, :create, :plans, :canceled, :thanks]
  before_filter :authorized?, :except => [ :new, :create, :plans, :canceled, :thanks]
  before_filter :build_user, :only => [:new, :create]
  before_filter :load_billing, :only => [ :billing ]
  before_filter :load_subscription, :only => [ :billing, :plan ]
  before_filter :load_discount, :only => [ :plans, :plan, :new, :create ]
  before_filter :build_plan, :only => [:new, :create]
  skip_before_filter :collect_billing_info

  def new
    # render :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
  end

  def create
    @account.affiliate = SubscriptionAffiliate.find_by_token(cookies[:affiliate]) unless cookies[:affiliate].blank?

    if @account.save
      flash[:domain] = @account.domain
      redirect_to thanks_url
    else
      render :action => 'new'#, :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
    end
  end

  def update
    if resource.update_attributes(params[:account].permit(:name))
      flash[:notice] = "Your account has been updated."
      redirect_to redirect_url
    else
      render :action => 'edit'
    end
  end

  def plans
    @plans = SubscriptionPlan.order('amount desc').collect {|p| p.discount = @discount; p }
    # render :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
  end

  def billing
    if request.post?
      result = if params[:stripeToken].present?
        @subscription.store_card(params[:stripeToken])
      else
        @address.first_name = @creditcard.first_name
        @address.last_name = @creditcard.last_name

        (@creditcard.valid? & @address.valid?) && @subscription.store_card(@creditcard, :billing_address => @address.to_activemerchant, :ip => request.remote_ip)
      end

      if result
        flash[:notice] = "Your billing information has been updated."
        redirect_to :action => "billing"
      end
    end
  end

  def plan
    if request.post?
      @subscription.plan = SubscriptionPlan.find(params[:plan_id])

      if @subscription.save
        flash[:notice] = "Your subscription has been changed."
        SubscriptionNotifier.plan_changed(@subscription).deliver
      else
        flash[:error] = "Error updating your plan: #{@subscription.errors.full_messages.to_sentence}"
      end
      redirect_to :action => "plan"
    else
      @plans = SubscriptionPlan.where(['id <> ?', @subscription.subscription_plan_id]).order('amount desc').collect {|p| p.discount = @subscription.discount; p }
    end
  end

  def cancel
    if request.post? and !params[:confirm].blank?
      current_account.destroy
      sign_out(:user)
      redirect_to :action => "canceled"
    end
  end

  def thanks
    redirect_to :action => "plans" and return unless flash[:domain]
    # render :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
  end

  def dashboard
  end

  protected

    def resource
      @account ||= current_account
    end

    def build_user
      build_resource.admin = User.new unless build_resource.admin
    end

    def build_plan
      redirect_to :action => "plans" unless @plan = SubscriptionPlan.find_by_name(params[:plan])
      @plan.discount = @discount
      @account.plan = @plan
    end

    def redirect_url
      { :action => 'show' }
    end

    def load_billing
      @creditcard = ActiveMerchant::Billing::CreditCard.new(params[:creditcard])
      @address = SubscriptionAddress.new(params[:address])
    end

    def load_subscription
      @subscription = current_account.subscription
    end

    # Load the discount by code, but not if it's not available
    def load_discount
      if params[:discount].blank? || !(@discount = SubscriptionDiscount.find_by_code(params[:discount])) || !@discount.available?
        @discount = nil
      end
    end

    def authorized?
      redirect_to new_user_session_url unless self.action_name == 'dashboard' || admin?
    end

    def permitted_params
      params.permit(:plan, :account => [ :name, :domain, :admin_attributes => [ :email, :password, :password_confirmation ] ])
    end

end

app/views/accounts/_credit_card_form.html.erb
<% if @creditcard.errors.full_messages.any? %>
  <div class="errorExplanation">
    <h2>Errors encountered with your payment information:</h2>
    <ul>
      <% @creditcard.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @address.errors.any? %>
  <div class="errorExplanation">
    <h2>Errors encountered with your address:</h2>
    <ul>
      <% @address.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @subscription && @subscription.errors.any? %>
  <div class="errorExplanation">
    <h2>Errors encountered with your payment:</h2>
    <ul>
      <% @subscription.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @creditcard, :as => :creditcard, :url => { :action => 'billing' }, :html => { :class => 'form-horizontal' } do |f| %>

  <fieldset>

    <div class="form-group">
      <label class="col-sm-2 control-label">Name on card</label>
      <div class="col-sm-10">
        <div class="col-xs-5"><%= text_field :creditcard, :first_name, :class => 'form-control' %></div>
        <div class="col-xs-5"><%= text_field :creditcard, :last_name, :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Card number</label>
      <div class="col-sm-10">
        <div class="col-xs-5"><%= text_field :creditcard, :number, :class => 'form-control', :required => true %></div>
        <div class="col-xs-5"><%= select :creditcard, :brand, Saas::Config.gateway == "bogus" ? [['Bogus', 'bogus']] : [['Visa', 'visa'], ['MasterCard', 'master'], ['American Express', 'american_express']], {}, :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Expiration</label>
      <div class="col-sm-10">
        <div class="col-xs-2"><%= select :creditcard, :month, (1 .. 12), {}, :class => 'form-control' %></div>
        <div class="col-xs-2"><%= select :creditcard, :year, (Time.now.year .. 10.years.from_now.year), {}, :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">CVV</label>
      <div class="col-sm-10">
        <div class="col-xs-2"><%= text_field :creditcard, :verification_value, :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Address</label>
      <div class="col-sm-10">
        <div class="col-xs-10"><%= text_field :address, :address1, :class => 'form-control', :required => true %></div>
        <div class="col-xs-10"><%= text_field :address, :address2, :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">City, State, Zip</label>
      <div class="col-sm-10">
        <div class="col-xs-3"><%= text_field :address, :city, :class => 'form-control', :required => true %></div>
        <div class="col-xs-3"><%= text_field :address, :state, :class => 'form-control' %></div>
        <div class="col-xs-3"><%= text_field :address, :zip, :class => 'form-control' %></div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Country</label>
      <div class="col-sm-10">
        <div class="col-xs-5"><%= country_select :address, :country, ['United States', 'Canada'], {}, :class => 'form-control', :required => true %></div>
      </div>
    </div>
  </fieldset>

  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-10">
      <div class="col-sm-10">
        <%= submit_or_cancel '/account', 'Update billing information', :disabled => (Saas::Config.gateway == 'stripe' and Saas::Config.credentials['stripe_publishable_key']) %>
      </div>
    </div>
  </div>
<% end %>


app/views/accounts/billing.html.erb
<h1><%= @page_title = 'View / Change Billing Information' %></h1>

<% if @subscription.state == 'trial' %>
  <% if @subscription.next_renewal_at > Time.now %>
    <p>
      Thank you for trying <%= Saas::Config.app_name %>!  Your trial account will expire in <%= pluralize(@subscription.trial_days, 'day', 'days') %>, at which time you will no longer have access to your account.  To maintain access to your account, enter your credit card information below.  Your first charge will happen on <%= @subscription.next_renewal_at.to_s(:long_day) %>.
    </p>
  <% else %>
    Thank you for trying <%= Saas::Config.app_name %>!  Your trial account has expired.  To regain access to your account, enter your credit card information below.  Your first charge will happen immediately, and you will be billed monthly thereafter.
  <% end %>
<% end %>

<fieldset>
  <label>Plan:</label>
  <%= @subscription.subscription_plan.name %> (<a href="/account/plan">Change plan</a>)
  
  <% if @subscription.state == 'trial' %>
    <label>Trial expiration date:</label>
    <%= @subscription.next_renewal_at.to_s(:long_day) %>
  <% else %>
    <% if @subscription.amount > 0 %>
      <label>Next charge date:</label>
      <%= @subscription.next_renewal_at.to_s(:long_day) %>
      <br/>
      <label>Next charge amount:</label>
      <%= number_to_currency @subscription.amount %>
      <br/>
      <label>Current payment method:</label>
      <%= "#{@subscription.card_number} / #{@subscription.card_expiration}" %>
    <% end %>
  <% end %>
</fieldset>

<% if @subscription.amount > 0 %>
  <%= render 'credit_card_form'  %>
<% end %>

<% content_for :head do %>
  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <%= javascript_include_tag 'stripe_form' %>
  <script type="text/javascript">
    // this identifies your website in the createToken call in stripe_form.js
    Stripe.setPublishableKey('<%= Saas::Config.credentials['stripe_publishable_key'] %>');
  </script>
<% end if Saas::Config.gateway == 'stripe' and Saas::Config.credentials['stripe_publishable_key'] %>

app/views/accounts/cancel.html.erb
<h1><%= @page_title = 'Cancel Account' %></h1>

<p>You are about to cancel your account.  This will <strong>permanently delete all your data</strong>.  Once you do this, you will no longer have access to your data, so be sure this is really what you want to do. </p>

<h2>Wait!  Before you go...</h2>
<p>
  Instead of canceling your account, perhaps you'd like to just switch your plan.  <a href="/account/plan">Change your subscription level now</a>.
</p>

<%= form_tag :action => 'cancel' do %>
  <fieldset>
    <legend>Cancel Confirmation</legend>

    <input type="checkbox" name="confirm" class="checkbox" value="1" />
    I really do want to cancel my account and delete all my data.
  </fieldset>

  <%= submit_or_cancel '/account', 'Delete my Account' %>
<% end %>

app/views/accounts/canceled.html.erb
<h1><%= @page_title = 'Account Canceled' %></h1>

<p>We're sorry to see you go, but your account has been canceled.</p>

app/views/accounts/dashboard.html.erb
<h1>Dashboard</h1>

<ul>
  <li><%= link_to "User Management", users_path %></li>
  <li><%= link_to "Account Settings", account_path %></li>
  <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
</ul>

app/views/accounts/edit.html.erb
<h1>Change account settings</h1>

<%= simple_form_for @account, :url => { :action => 'update' }, :html => { :method => :put } do |f| %>
  <%= f.input :name %>
  <%= submit_or_cancel :action => 'show' %>
<% end %>

app/views/accounts/new.html.erb
<h1>Create an account</h1>

<%= simple_form_for @account, :url => { :action => 'create' } do |account| %>
  <%= hidden_field_tag 'plan', params[:plan] %>
  <p>
    Enter the name of your business and the subdomain you'd like to use for your site.
  </p>
  
  <% if @account.errors.any? %>
    <div class="alert alert-warning">Some errors were encountered while creating your account</div>
  <% end %>

  <fieldset>
    <%= account.input :name %>
    <%= account.input :domain, hint: raw(%Q{Your domain will be http://<span id="subdomain">#{@account.domain.present? ? @account.domain : 'something'}</span>.#{Saas::Config.base_domain}}) %>
  </fieldset>

  <p>
    Enter info for the administrator account.
  </p>

  <fieldset>  
    <%= account.simple_fields_for :admin do |admin| %>
      <%= admin.input :email %>
      <%= admin.input :password %>
      <%= admin.input :password_confirmation %>
    <% end %>
  </fieldset>

  <% if @account.needs_payment_info? %>
    <p>
      Your payment info will be collected after you have created your account and logged in.
    </p>

    <p>
      You will be charged <%= number_to_currency(@account.plan.setup_amount) + ' now and ' if  @account.plan.setup_amount? && !@account.plan.trial_period? %>
      <%= number_to_currency(@account.plan.amount) %> <%= @account.plan.renewal_period == 1 ? 'every month' : "every #{@account.plan.renewal_period} months" %>
      for the <%= @account.plan.name %> plan
      <%= @account.plan.trial_period? ? 'after the trial period' : 'starting immediately' %>.
    </p>

  <% end %>

  <fieldset>
    <input type="submit" value="Create my account" />
  </fieldset>

<% end %>

app/views/accounts/plan.html.erb
<% if @subscription && @subscription.errors.any? %>
  <div class="errorExplanation">
    <h2>Errors encountered with your change:</h2>
    <ul>
      <%= raw(@subscription.errors.full_messages.map {|m| content_tag('li', m)}) %>
    </ul>
  </div>
<% end %>

<h1><%= @page_title = 'Change Plan' %></h1>

<p>
  You can change your plan level at any time.  The position limits and other features of the new plan that you select will be effective as soon as you make the change, but your bill amount will not change until your next bill date.  Your next bill date is <%= @subscription.next_renewal_at.to_s(:long_day) %>.
</p>

<% if @subscription.needs_payment_info? -%>
  <p>
    Please make sure you <%= link_to('enter your billing information', billing_account_url) %> before your bill date to prevent an interruption in service.
  </p>
<% end %>


<p style="padding-top:1em">
  You are currently subscribed to the <strong><%= @subscription.subscription_plan.name %> Plan</strong>.  Please select your desired plan and click the "Change my plan" button.
</p>

<%= form_tag plan_account_url do %>
  <fieldset>
    <legend>Choose Plan</legend>
    <select name="plan_id" onChange="enableButton()">
      <option value=""></option>
      <% @plans.each do |plan| %>
        <option value="<%= plan.id %>"<%= 'disabled="disabled"' unless current_account.qualifies_for?(plan) %>><%= plan %></option>
      <% end %>
    </select>
    
  </fieldset>

  <fieldset id="submit_or_cancel"><input name="commit" type="submit" id="commit" disabled="disabled" value="Change my plan" class="btn btn-primary"/> or <a href="/account">Cancel</a></fieldset>
<% end %>
  
<script type="text/javascript" charset="utf-8">
  function enableButton() {
    document.getElementById('commit').disabled = document.forms[0].elements['plan_id'].selectedIndex == 0
  }
  enableButton();
</script>

app/views/accounts/plans.html.erb
<% # Plan grid from http://bootsnipp.com/snippets/featured/plans-and-pricing %>
<h1>Plans</h1>

<div class="row" id="plan-grid">
  <% @plans.each do |plan| %>
    <div class="col-xs-12 col-md-<%= 12 / @plans.size %>">
      <div class="panel panel-primary">
        <% if plan == @plans[1] %>
          <div class="cnrflash">
            <div class="cnrflash-inner">
              <span class="cnrflash-label">MOST <br> POPULAR</span>
            </div>
          </div>
        <% end %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= plan.name %></h3>
        </div>
        <div class="panel-body">
          <div class="the-price">
            <h1> <%= number_to_currency(plan.amount) %><span class="subscript">/mo</span></h1>
            <% if plan.amount > 0 %>
              <small>1 month FREE trial</small>
            <% else %>
              <small>FREE forever :)</small>
            <% end %>
          </div>
          <table class="table">
            <tr>
              <td>
                <%= plan.user_limit.nil? ? 'Unlimited Users' : pluralize(plan.user_limit, 'User') %>
              </td>
            </tr>
          </table>
        </div>
        <div class="panel-footer">
          <%= link_to("Sign Up", new_account_url(:plan => plan, :discount => params[:discount]), :class => "btn btn-success") %>
          <%= "1 month FREE trial" if plan.amount > 0 %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/accounts/show.html.erb
<h1>Account Settings</h1>

<ul>
  <li><%= link_to('Edit account', edit_account_url) %></li>
  <li><%= link_to('Change plan', plan_account_url) %></li>
  <li><%= link_to('Billing info', billing_account_url) %></li>
  <li><%= link_to('Cancel account', cancel_account_url) %></li>
</ul>

app/views/accounts/thanks.html.erb
<h1>Account created</h1>

<p>
  Thank you for creating an account!  You can now log in to your account at <a href="http://<%= flash[:domain] %>.<%= request.host_with_port %>/">http://<%= flash[:domain] %>.<%= request.host_with_port %>/</a>.
</p>